config/routes.rb
    match '/body/list/all' => 'public_body#list', :as => :list_public_bodies_default
    match '/body/list/:tag' => 'public_body#list', :as => :list_public_bodies
    match '/local/:tag' => 'public_body#list_redirect', :as => :list_public_bodies_redirect
    match '/body/all-authorities.csv' => 'public_body#list_all_csv', :as => :all_public_bodies_csv
    match '/body/:url_name' => 'public_body#show', :as => :show_public_body, :view => 'all'
    match '/body/:url_name/all' => 'public_body#show', :as => :show_public_body_all, :view => 'all'
    match '/body/:url_name/successful' => 'public_body#show', :as => :show_public_body_successful, :view => 'successful'
    match '/body/:url_name/unsuccessful' => 'public_body#show', :as => :show_public_body_unsuccessful, :view => 'unsuccessful'
    match '/body/:url_name/awaiting' => 'public_body#show', :as => :show_public_body_awaiting, :view => 'awaiting'
    match '/body/:url_name/view_email' => 'public_body#view_email', :as => :view_public_body_email
    match '/body/:url_name/:tag' => 'public_body#show', :as => :show_public_body_tag
    match '/body/:url_name/:tag/:view' => 'public_body#show', :as => :show_public_body_tag_view
    match '/body_statistics' => 'public_body#statistics', :as => :public_bodies_statistics
    ####

    resource :change_request, :only => [:new, :create], :controller => 'public_body_change_requests'

    #### Comment controller
    match '/annotate/request/:url_title' => 'comment#new', :as => :new_comment, :type => 'request'
    ####

    #### Services controller
    match '/country_message' => 'services#other_country_message', :as => :other_country_message
    match '/hidden_user_explanation' => 'services#hidden_user_explanation', :as => :hidden_user_explanation
    ####

    #### Track controller
    # /track/ is for setting up an email alert for the item
    # /feed/ is a direct RSS feed of the item
    match '/:feed/request/:url_title' => 'track#track_request', :as => :track_request, :feed => /(track|feed)/
    match '/:feed/list/:view' => 'track#track_list', :as => :track_list, :view => nil, :feed => /(track|feed)/
    match '/:feed/body/:url_name' => 'track#track_public_body', :as => :track_public_body, :feed => /(track|feed)/
    match '/:feed/user/:url_name' => 'track#track_user', :as => :track_user, :feed => /(track|feed)/
    # TODO: :format doesn't work. See hacky code in the controller that makes up for this.
    match '/:feed/search/:query_array' => 'track#track_search_query',
          :as => :track_search,
          :feed => /(track|feed)/,
          :constraints => { :query_array => /.*/ }

    match '/track/update/:track_id' => 'track#update', :as => :update
    match '/track/delete_all_type' => 'track#delete_all_type', :as => :delete_all_type
    match '/track/feed/:track_id' => 'track#atom_feed', :as => :atom_feed
    match '/track/widget_vote/:info_request_id' => 'track#widget_vote', :as => :widget_vote
    ####

    #### Help controller
    match '/help/unhappy/:url_title' => 'help#unhappy', :as => :help_unhappy
    match '/help/about' => 'help#about', :as => :help_about
    match '/help/alaveteli' => 'help#alaveteli', :as => :help_alaveteli
    match '/help/contact' => 'help#contact', :as => :help_contact
    match '/help/officers' => 'help#officers', :as => :help_officers
    match '/help/requesting' => 'help#requesting', :as => :help_requesting
    match '/help/privacy' => 'help#privacy', :as => :help_privacy
    match '/help/api' => 'help#api', :as => :help_api
    match '/help/credits' => 'help#credits', :as => :help_credits
    match '/help/:action' => 'help#action', :as => :help_general
    match '/help' => 'help#index'
    ####

    #### Holiday controller
    match '/due_date/:holiday' => 'holiday#due_date', :as => :due_date
    ####

    #### RequestGame controller
    match '/categorise/play' => 'request_game#play', :as => :categorise_play
    match '/categorise/request/:url_title' => 'request_game#show', :as => :categorise_request
    match '/categorise/stop' => 'request_game#stop', :as => :categorise_stop
    ####

    #### AdminPublicBody controller
    scope '/admin', :as => 'admin' do
        resources :bodies,
                  :controller => 'admin_public_body' do
                    get 'missing_scheme', :on => :collection
                    post 'mass_tag_add', :on => :collection
                    get 'import_csv', :on => :collection
                    post 'import_csv', :on => :collection
        end
    end
    ####

    #### AdminPublicBodyCategory controller
    scope '/admin', :as => 'admin' do
        resources :categories,
                  :controller => 'admin_public_body_categories'
    end
    ####

    #### AdminPublicBodyHeading controller
    scope '/admin', :as => 'admin'  do
        resources :headings,
                  :controller => 'admin_public_body_headings',
                  :except => [:index] do
                      post 'reorder', :on => :collection
                      post 'reorder_categories', :on => :member
        end
    end
    ####

    #### AdminHoliday controller
    scope '/admin', :as => 'admin' do
        resources :holidays,
                  :controller => 'admin_holidays'
    end
    ####

    #### AdminHolidayImports controller
    scope '/admin', :as => 'admin' do
      resources :holiday_imports,
                :controller => 'admin_holiday_imports',
                :only => [:new, :create]
    end
    ####

    #### AdminPublicBodyChangeRequest controller
    scope '/admin', :as => 'admin'  do
        resources :change_requests,
                  :controller => 'admin_public_body_change_requests',
                  :only => [:edit, :update]
    end
    ####

    #### AdminGeneral controller
    match '/admin' => 'admin_general#index', :as => :admin_general_index
    match '/admin/timeline' => 'admin_general#timeline', :as => :admin_timeline
    match '/admin/debug' => 'admin_general#debug', :as => :admin_debug
    match '/admin/stats' => 'admin_general#stats', :as => :admin_stats
    ####

    #### AdminRequest controller
    scope '/admin', :as => 'admin' do
        resources :requests,
                  :controller => 'admin_request',
                  :except => [:new, :create] do
                      post 'move', :on => :member
                      post 'generate_upload_url', :on => :member
                      post 'hide', :on => :member
                      resources :censor_rules,
                                :controller => 'admin_censor_rule',
                                :only => [:new, :create],
                                :name_prefix => 'request_'

        end
    end
    ####

    #### AdminComment controller
    scope '/admin', :as => 'admin' do
        resources :comments,
                  :controller => 'admin_comment',
                  :only => [:edit, :update]
    end
    ####

    #### AdminRawEmail controller
    scope '/admin', :as => 'admin' do
        resources :raw_emails,
                  :controller => 'admin_raw_email',
                  :only => [:show]
    end
    ####

    #### AdminInfoRequestEvent controller
    scope '/admin', :as => 'admin' do
        resources :info_request_events,
                  :controller => 'admin_info_request_event',
                  :only => [:update]
    end

    #### AdminIncomingMessage controller
    scope '/admin', :as => 'admin' do
        resources :incoming_messages,
                  :controller => 'admin_incoming_message',
                  :only => [:edit, :update, :destroy] do
                      post 'redeliver', :on => :member
        end
    end
    ####

    #### AdminOutgoingMessage controller
    scope '/admin', :as => 'admin' do
        resources :outgoing_messages,
                :controller => 'admin_outgoing_message',
                :only => [:edit, :update, :destroy] do
                    post 'resend', :on => :member
        end
    end
    ####

    #### AdminUser controller
    scope '/admin', :as => 'admin' do
        resources :users,
                :controller => 'admin_user',
                :except => [:new, :create, :destroy] do
                    get 'banned', :on => :collection
                    get 'show_bounce_message', :on => :member
                    post 'clear_bounce', :on => :member
                    post 'login_as', :on => :member
                    post 'clear_profile_photo', :on => :member
                    post 'modify_comment_visibility', :on => :collection
                    resources :censor_rules,
                              :controller => 'admin_censor_rule',
                              :only => [:new, :create],
                              :name_prefix => 'user_'
        end
    end
    ####

    #### AdminTrack controller
    scope '/admin', :as => 'admin' do
        resources :tracks,
            :controller => 'admin_track',
            :only => [:index, :destroy]
    end
    ####

    #### AdminCensorRule controller
    scope '/admin', :as => 'admin' do
        resources :censor_rules,
                  :controller => 'admin_censor_rule',
                  :except => [:index, :new, :create]
    end

    #### AdminSpamAddresses controller
    scope '/admin', :as => 'admin' do
        resources :spam_addresses,
                  :controller => 'admin_spam_addresses',
                  :only => [:index, :create, :destroy]
    end
    ####

    #### Api controller
    match '/api/v2/request.json' => 'api#create_request', :as => :api_create_request, :via => :post

    match '/api/v2/request/:id.json' => 'api#show_request', :as => :api_show_request, :via => :get
    match '/api/v2/request/:id.json' => 'api#add_correspondence', :as => :api_add_correspondence, :via => :post
    match '/api/v2/request/:id/update.json' => 'api#update_state', :as => :api_update_state, :via => :post

app/controllers/admin_raw_email_controller.rb
# -*- encoding : utf-8 -*-
# app/controllers/admin_raw_email_controller.rb:
# Controller for managing raw emails from the admin interface.
#
# Copyright (c) 2007 UK Citizens Online Democracy. All rights reserved.
# Email: hello@mysociety.org; WWW: http://www.mysociety.org/

class AdminRawEmailController < AdminController

    def show
        @raw_email = RawEmail.find(params[:id])
        respond_to do |format|
            format.html do
                # For the holding pen, try to guess where it should be ...
                @holding_pen = false
                if (@raw_email.incoming_message.info_request == InfoRequest.holding_pen_request && !@raw_email.incoming_message.empty_from_field?)
                    @holding_pen = true

                    # 1. Use domain of email to try and guess which public body it
                    # is associated with, so we can display that.
                    email = @raw_email.incoming_message.from_email
                    domain = PublicBody.extract_domain_from_email(email)

                    if domain.nil?
                        @public_bodies = []
                    else
                        @public_bodies = PublicBody.find(:all, :order => "name",
                            :conditions => [ "lower(request_email) like lower('%'||?||'%')", domain ])
                    end

                    # 2. Match the email address in the message without matching the hash
                    @info_requests =  InfoRequest.guess_by_incoming_email(@raw_email.incoming_message)

                    # 3. Give a reason why it's in the holding pen
                    last_event = InfoRequestEvent.find_by_incoming_message_id(@raw_email.incoming_message.id)
                    @rejected_reason = last_event.params[:rejected_reason] || "unknown reason"
                end
            end
            format.text do
                response.content_type = 'message/rfc822'
                render :text => @raw_email.data
            end
        end
    end

end

app/views/admin_raw_email/show.html.erb
<%= render :partial => 'admin_incoming_message/intro', :locals => { :incoming_message => @raw_email.incoming_message } %>

    <% if @holding_pen %>
        <br>This is in the holding pen because: <strong><%= @rejected_reason %></strong>
        <% if @public_bodies.size > 0 %>
            <br>Guessed authority:
            <% @public_bodies.each do |public_body| %>
                <%=public_body_both_links(public_body)%>
            <% end %>
            (based on From: email domain)
        <% end %>
        <% if @info_requests.size > 0 %>
            <div class="accordion" id="guessed-requests">
                Guessed request:
                <% @info_requests.each do |info_request|  %>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a href="#info_request_<%= info_request.id %>" data-toggle="collapse"><i class="icon-chevron-right"></i></a>
                            <%=request_both_links(info_request)%>
                        </div>
                        <div class="accordion-body collapse" id="info_request_<%= info_request.id %>">
                            <table class="table table-striped table-condensed">
                                <tr>
                                    <td><strong>Last outgoing message:</strong></td>
                                    <td><%= info_request.outgoing_messages.last.body %></td>
                                </tr>
                                <tr>
                                    <td><strong>Created by:</strong></td>
                                    <td><%= user_admin_link_for_request(info_request) %></td>
                                </tr>
                                <tr>
                                    <td><strong>Authority:</strong></td>
                                    <td>
                                        <%= link_to(info_request.public_body.name, admin_body_path(info_request.public_body)) %>
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>url_title:</strong></td>
                                    <td><%= info_request.url_title %></td>
                                </tr>
                            </table>
                            <p>
                                This request was guessed because it has an incoming email address of <strong><%= info_request.incoming_email %></strong> and this incoming message was sent to <strong><%= @raw_email.incoming_message.mail.to %></strong>.
                            </p>
                        </div>
                    </div>
                <% end %>
                (based on id, not hash, in To/Cc email)
            </div>
        <% end %>
    <% end %>
</p>

<div>
    <%= render :partial => 'admin_incoming_message/actions', :locals => { :incoming_message => @raw_email.incoming_message } %>
</div>

<h2>Raw email</h2>

<p><%= link_to "Download",  admin_raw_email_path(@raw_email, :format => 'txt') %></p>

<h2>Preview</h2>

For an exact rendering of this email, use the "Download" link.
<pre><%=h(@raw_email.data_as_text).gsub(/\n/, '<br>').html_safe %></pre>